name: build

on:
  push:
    branches-ignore:
      - dev
  pull_request:
    branches-ignore:
      - dev
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        preset: [Release]
    runs-on: ${{ matrix.os }}
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    # fetch latest cmake
    - uses: lukka/get-cmake@v3.31.6

    - name: Build release package
      run: sh ./build_release.sh

    - name: Deploy
      if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}
      uses: actions/upload-artifact@master
      with:
        name: sphaira-${{ matrix.preset }}
        path: |
          build/${{ matrix.preset }}/sphaira.nro
          out/sphaira.zip
